<?php
  require_once('connection.php');
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('hematoma', '두혈종', '머리', 'head')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('headasymmetric', '비대칭', '머리', 'head')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('fontanelle', '대천문함몰', '머리', 'head')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('salmon', '연어반', '얼굴', 'face')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('nasal', '비강상태', '얼굴', 'face')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('facesecretion', '분비물', '얼굴', 'face')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('irugong', '이루공', '얼굴', 'face')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('torticollis', '사경', '얼굴', 'face')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('pearl', '진주종', '구강', 'oral')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('singlesnow', '단설소대', '구강', 'oral')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('thrush', '아구창', '구강', 'oral')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('jawBalance', '턱 균형', '구강', 'oral')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('cheskDent', '흉관함몰', '가슴', 'chest')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('glandMastitis', '젖 몽우리', '가슴', 'chest')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('claviclefracture', '쇄골골절', '가슴', 'chest')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('shoulderdislocation', '어깨탈골', '가슴', 'chest')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('redness', '발적', '배꼽', 'code')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('codesecretion', '분비물', '배꼽', 'code')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('diaperrash', '기저귀 발진', '엉덩이', 'hip')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('dimple', 'Dimple', '엉덩이', 'hip')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('inguinalwrinkles', '서혜부주름 대칭', '엉덩이', 'hip')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('latenttesticles', '잠복고환', '비뇨기', 'urology')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('scrotum', '음낭수종', '비뇨기', 'urology')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('urethralhigh', '요도 상열', '비뇨기', 'urology')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('urethrallow', '요도 하열', '비뇨기', 'urology')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('outside', 'hallucinations', '외반', '팔, 다리', 'armleg')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('inside', '내반', '팔, 다리', 'armleg')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('asymmetriclegarms', '비대칭', '팔, 다리', 'armleg')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('periphery', '생인손', '손', 'hand')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('hyperhidrosis', '다지증', '손', 'hand')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('dizziness', '합지증', '손', 'hand')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('juandice', '황달', '피부', 'skin')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('dryskin', '건조', '피부', 'skin')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('congenitalfever', '태열', '피부', 'skin')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('wound', '상처', '피부', 'skin')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('diarrhea', '설사', '대변상태', 'feces')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('fever', '열', '기타', 'etc')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('hepatitisb', 'B형간염1차', '예방접종', 'vaccination')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('bcg', 'BCG', '예방접종', 'vaccination')";
  $result=mysqli_query($conn, $sql);
  $sql = "INSERT INTO n_symptom(ename, name, kind, ekind) VALUES('congenitalmetabolicdisorder', '선천성대사 이상 검사', '예방접종', 'vaccination')";
  $result=mysqli_query($conn, $sql);

  if($result === false){
    echo '저장하는 과정에서 문제가 생겼습니다. 관리자에게 문의해주세요';
    error_log(mysqli_error($conn));
    echo mysqli_error($conn);
  }else{
    echo 'well done';
  }
?>
